### Create Size
POST http://localhost:3000/size/create
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhhYjU0MjAxLWQ5YTUtNDE2Zi04MTllLWFjNTg0Yzk4YmI3NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3JydWRtaHV0amVkdHB2dWdweGFtLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZGE5ODU1MS0zMWU3LTQyNWEtOTBiZC02MmJkOTMyYWNjZDIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyNTUxMjM0LCJpYXQiOjE3ODI1NDc2MzQsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjhkYTk4NTUxLTMxZTctNDI1YS05MGJkLTYyYmQ5MzJhY2NkMiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgyNTQ3NjM0fV0sInNlc3Npb25faWQiOiJkNDA0ZTBjZC0wMDNlLTQ2ZWMtYWI1NC0zZDA0NDJlODAzN2MiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.WQ476WOUzfs5fAqGzYga2NimHshQ0jTmrAEPYxCJYH46gP6v-1KsMfo3IkqwDU2M4tI4xQBTze4CaD7thRj3Jw
Content-Type: application/json

{
    "size_name": "S"
}
